# Generated by Django 6.0.4 on 2026-05-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ecomm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created_at',
            new_name='cart_created_at',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='cart_product',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='cart_quantity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='ord_shipping_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='ord_status',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='pr_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_featured',
            new_name='pr_is_featured',
        ),
    ]
