# Generated by Django 6.0.5 on 2026-05-25 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ecomm_app', '0002_rename_created_at_cart_cart_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pr_is_featured',
            new_name='is_featured',
        ),
        migrations.AlterField(
            model_name='order',
            name='ord_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Order's Creation Date"),
        ),
        migrations.AlterField(
            model_name='order',
            name='ord_shipping_address',
            field=models.TextField(verbose_name="Order's Shipping Address"),
        ),
        migrations.AlterField(
            model_name='order',
            name='ord_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20, verbose_name="Order's Status"),
        ),
        migrations.AlterField(
            model_name='order',
            name='ord_total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Order's Total Price"),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='django_ecomm_app.category', verbose_name="Product's Category"),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Product's Creation Date"),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_description',
            field=models.TextField(blank=True, verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name="Product's Image"),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_name',
            field=models.CharField(max_length=150, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_old_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Product's Old Price"),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Product's Price"),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Product Stock'),
        ),
    ]
