# Generated by Django 6.0.4 on 2026-05-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ecomm_app', '0003_rename_pr_is_featured_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ord_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20, verbose_name="Order's Status"),
        ),
    ]
