# Generated by Django 6.0.4 on 2026-05-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ecomm_app', '0004_alter_order_ord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ord_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20, verbose_name="Order's Status"),
        ),
    ]
