# Generated by Django 6.0.5 on 2026-05-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ecomm_app', '0005_alter_order_ord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pr_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
